Repository heyhikkie/Web-Dev-Projects-Level-2, pull requests merged in 2023-10, with the labels that each got.

#3 TodoList Project
  TodoList/WebToDoList.html
  TodoList/bootstrap.min.css
  TodoList/wtd.jpg
  TodoList/wtdJS.js
  TodoList/wtdSTYLE.css
Labels: hactoberfest, hactoberfest-accepted, hacktoberfest-accepted

#4 Tribute Project
  Tribute/Tribute.html
  Tribute/WingsOfFire.jpg
Labels: help wanted, hactoberfest, hactoberfest-accepted, hacktoberfest-accepted

#6 Contact Form - Arpita
  ContactForm/app.js
  ContactForm/img/img.jpg
  ContactForm/img/logo-forDark.png
  ContactForm/img/logo-forLight.png
  ContactForm/img/wave.png
  ContactForm/index.html
  ContactForm/style.css
Labels: hacktoberfest-accepted

#13 GIF Generator
  GIF Generator/.env
  GIF Generator/.gitignore
  GIF Generator/README.md
  GIF Generator/package-lock.json
  GIF Generator/package.json
  GIF Generator/public/android-chrome-192x192.png
  GIF Generator/public/android-chrome-512x512.png
  GIF Generator/public/apple-touch-icon.png
  GIF Generator/public/favicon-16x16.png
  GIF Generator/public/favicon-32x32.png
  GIF Generator/public/favicon.ico
  GIF Generator/public/index.html
  GIF Generator/public/robots.txt
  GIF Generator/public/site.webmanifest
  GIF Generator/src/App.jsx
  GIF Generator/src/components/Random.js
  GIF Generator/src/components/Spinner.js
  GIF Generator/src/components/Tag.js
  GIF Generator/src/hooks/useGif.js
  GIF Generator/src/index.css
  GIF Generator/src/index.js
  GIF Generator/tailwind.config.js
Labels: hacktoberfest-accepted
